/**
	All Rights Reserved,(c) JACIC 2001
	ファイル名				作成日：2000.04.24
	SXFExtraSchema.H

	１．機能概要
	　　スキーマを解釈した結果得られた
	　　各エンティティのデータ構造を定義する。

	２．履歴
	履歴番号		日付け		担当者		概要
	作成		2000.04.24	　　藤本（FQS）	　　なし。

**/
ENTITY(SXFDict_FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE)
	NAME("FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("SYMBOL","ANNOTATION_SYMBOL_OCCURRENCE");
END_ENTITY

ENTITY(SXFDict_MEASURE_WITH_UNIT)
	NAME("MEASURE_WITH_UNIT");
	ATTRIBUTE("VALUE_COMPONENT","MEASURE_VALUE");
	ATTRIBUTE("UNIT_COMPONENT","UNIT");
END_ENTITY

TYPEDEF(SXFDict_PARAMETER_VALUE,"PARAMETER_VALUE","REAL")

ENTITY(SXFDict_COMPOSITE_CURVE)
	NAME("COMPOSITE_CURVE");
	SUBTYPE_OF("BOUNDED_CURVE");
	ATTRIBUTE("SEGMENTS","LIST [ 1 : ? ] OF COMPOSITE_CURVE_SEGMENT");
	ATTRIBUTE("SELF_INTERSECT","LOGICAL");
END_ENTITY

ENUMERATION(SXFDict_CENTRAL_OR_PARALLEL)
	NAME("CENTRAL_OR_PARALLEL");
	ENUMITEM("CENTRAL");
	ENUMITEM("PARALLEL");
END_ENUMERATION

ENTITY(SXFDict_DRAUGHTING_PRE_DEFINED_COLOUR)
	NAME("DRAUGHTING_PRE_DEFINED_COLOUR");
	SUBTYPE_OF("PRE_DEFINED_COLOUR");
END_ENTITY

ENTITY(SXFDict_SYMBOL_COLOUR)
	NAME("SYMBOL_COLOUR");
	ATTRIBUTE("COLOUR_OF_SYMBOL","COLOUR");
END_ENTITY

ENTITY(SXFDict_TEXT_LITERAL)
	NAME("TEXT_LITERAL");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("LITERAL","PRESENTABLE_TEXT");
	ATTRIBUTE("PLACEMENT","AXIS2_PLACEMENT");
	ATTRIBUTE("ALIGNMENT","TEXT_ALIGNMENT");
	ATTRIBUTE("PATH","TEXT_PATH");
	ATTRIBUTE("FONT","FONT_SELECT");
END_ENTITY

ENTITY(SXFDict_CURVE)
	NAME("CURVE");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
END_ENTITY

SELECT(SXFDict_STYLE_CONTEXT_SELECT)
	NAME("STYLE_CONTEXT_SELECT");
	SELECTITEM("REPRESENTATION");
	SELECTITEM("REPRESENTATION_ITEM");
	SELECTITEM("PRESENTATION_SET");
END_SELECT

ENTITY(SXFDict_DRAUGHTING_SUBFIGURE_REPRESENTATION)
	NAME("DRAUGHTING_SUBFIGURE_REPRESENTATION");
	SUBTYPE_OF("SYMBOL_REPRESENTATION");
END_ENTITY

TYPEDEF(SXFDict_TEXT_DELINEATION,"TEXT_DELINEATION","LABEL")

TYPEDEF(SXFDict_RATIO_MEASURE,"RATIO_MEASURE","REAL")

ENTITY(SXFDict_PLANAR_BOX)
	NAME("PLANAR_BOX");
	SUBTYPE_OF("PLANAR_EXTENT");
	ATTRIBUTE("PLACEMENT","AXIS2_PLACEMENT");
END_ENTITY

ENTITY(SXFDict_EXTERNALLY_DEFINED_ITEM)
	NAME("EXTERNALLY_DEFINED_ITEM");
	ATTRIBUTE("ITEM_ID","SOURCE_ITEM");
	ATTRIBUTE("SOURCE","EXTERNAL_SOURCE");
END_ENTITY

ENTITY(SXFDict_NAMED_UNIT)
	NAME("NAMED_UNIT");
	ATTRIBUTE("DIMENSIONS","DIMENSIONAL_EXPONENTS");
END_ENTITY

SELECT(SXFDict_VECTOR_OR_DIRECTION)
	NAME("VECTOR_OR_DIRECTION");
	SELECTITEM("VECTOR");
	SELECTITEM("DIRECTION");
END_SELECT

ENTITY(SXFDict_SYMBOL_TARGET)
	NAME("SYMBOL_TARGET");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("PLACEMENT","AXIS2_PLACEMENT");
	ATTRIBUTE("X_SCALE","POSITIVE_RATIO_MEASURE");
	ATTRIBUTE("Y_SCALE","POSITIVE_RATIO_MEASURE");
END_ENTITY

ENTITY(SXFDict_PRE_DEFINED_ITEM)
	NAME("PRE_DEFINED_ITEM");
	ATTRIBUTE("NAME","LABEL");
END_ENTITY

ENUMERATION(SXFDict_ANGLE_RELATOR)
	NAME("ANGLE_RELATOR");
	ENUMITEM("EQUAL");
	ENUMITEM("LARGE");
	ENUMITEM("SMALL");
END_ENUMERATION

SELECT(SXFDict_CLASSIFIED_ITEM)
	NAME("CLASSIFIED_ITEM");
	SELECTITEM("DRAWING_REVISION");
	SELECTITEM("DRAWING_SHEET_REVISION");
END_SELECT

ENTITY(SXFDict_REPRESENTATION_ITEM)
	NAME("REPRESENTATION_ITEM");
	ATTRIBUTE("NAME","LABEL");
END_ENTITY

ENTITY(SXFDict_POINT)
	NAME("POINT");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
END_ENTITY

SELECT(SXFDict_SIZE_SELECT)
	NAME("SIZE_SELECT");
	SELECTITEM("POSITIVE_LENGTH_MEASURE");
	SELECTITEM("MEASURE_WITH_UNIT");
END_SELECT

ENUMERATION(SXFDict_DIMENSION_EXTENT_USAGE)
	NAME("DIMENSION_EXTENT_USAGE");
	ENUMITEM("ORIGIN");
	ENUMITEM("TARGET");
END_ENUMERATION

SELECT(SXFDict_CHARACTER_SPACING_SELECT)
	NAME("CHARACTER_SPACING_SELECT");
	SELECTITEM("LENGTH_MEASURE");
	SELECTITEM("MEASURE_WITH_UNIT");
END_SELECT

ENTITY(SXFDict_POLYLINE)
	NAME("POLYLINE");
	SUBTYPE_OF("BOUNDED_CURVE");
	ATTRIBUTE("POINTS","LIST [ 2 : ? ] OF CARTESIAN_POINT");
END_ENTITY

ENTITY(SXFDict_LEADER_DIRECTED_CALLOUT)
	NAME("LEADER_DIRECTED_CALLOUT");
	SUBTYPE_OF("DRAUGHTING_CALLOUT");
END_ENTITY

ENTITY(SXFDict_MAPPED_ITEM)
	NAME("MAPPED_ITEM");
	SUBTYPE_OF("REPRESENTATION_ITEM");
	ATTRIBUTE("MAPPING_SOURCE","REPRESENTATION_MAP");
	ATTRIBUTE("MAPPING_TARGET","REPRESENTATION_ITEM");
END_ENTITY

SELECT(SXFDict_DEFINED_SYMBOL_SELECT)
	NAME("DEFINED_SYMBOL_SELECT");
	SELECTITEM("PRE_DEFINED_SYMBOL");
	SELECTITEM("EXTERNALLY_DEFINED_SYMBOL");
END_SELECT

ENTITY(SXFDict_DIMENSION_PAIR)
	NAME("DIMENSION_PAIR");
	SUBTYPE_OF("DRAUGHTING_CALLOUT_RELATIONSHIP");
END_ENTITY

ENTITY(SXFDict_BOUNDED_CURVE)
	NAME("BOUNDED_CURVE");
	SUBTYPE_OF("CURVE");
END_ENTITY

SELECT(SXFDict_CURVE_OR_ANNOTATION_CURVE_OCCURRENCE)
	NAME("CURVE_OR_ANNOTATION_CURVE_OCCURRENCE");
	SELECTITEM("CURVE");
	SELECTITEM("ANNOTATION_CURVE_OCCURRENCE");
END_SELECT

ENTITY(SXFDict_PRE_DEFINED_SYMBOL)
	NAME("PRE_DEFINED_SYMBOL");
	SUBTYPE_OF("PRE_DEFINED_ITEM");
END_ENTITY

ENTITY(SXFDict_PRE_DEFINED_TERMINATOR_SYMBOL)
	NAME("PRE_DEFINED_TERMINATOR_SYMBOL");
	SUBTYPE_OF("PRE_DEFINED_SYMBOL");
END_ENTITY

ENTITY(SXFDict_PRE_DEFINED_POINT_MARKER_SYMBOL)
	NAME("PRE_DEFINED_POINT_MARKER_SYMBOL");
	SUBTYPE_OF("PRE_DEFINED_SYMBOL");
	SUBTYPE_OF("PRE_DEFINED_MARKER");
END_ENTITY

ENTITY(SXFDict_GLOBAL_UNIT_ASSIGNED_CONTEXT)
	NAME("GLOBAL_UNIT_ASSIGNED_CONTEXT");
	SUBTYPE_OF("REPRESENTATION_CONTEXT");
	ATTRIBUTE("UNITS","SET [ 1 : ? ] OF UNIT");
END_ENTITY

ENUMERATION(SXFDict_SI_PREFIX)
	NAME("SI_PREFIX");
	ENUMITEM("EXA");
	ENUMITEM("PETA");
	ENUMITEM("TERA");
	ENUMITEM("GIGA");
	ENUMITEM("MEGA");
	ENUMITEM("KILO");
	ENUMITEM("HECTO");
	ENUMITEM("DECA");
	ENUMITEM("DECI");
	ENUMITEM("CENTI");
	ENUMITEM("MILLI");
	ENUMITEM("MICRO");
	ENUMITEM("NANO");
	ENUMITEM("PICO");
	ENUMITEM("FEMTO");
	ENUMITEM("ATTO");
END_ENUMERATION

SELECT(SXFDict_DRAUGHTING_TITLED_ITEM)
	NAME("DRAUGHTING_TITLED_ITEM");
	SELECTITEM("DRAWING_REVISION");
	SELECTITEM("DRAWING_SHEET_REVISION");
END_SELECT

SELECT(SXFDict_APPROVED_ITEM)
	NAME("APPROVED_ITEM");
	SELECTITEM("DRAWING_REVISION");
	SELECTITEM("DRAWING_SHEET_REVISION");
END_SELECT

ENTITY(SXFDict_EXTERNAL_SOURCE)
	NAME("EXTERNAL_SOURCE");
	ATTRIBUTE("SOURCE_ID","SOURCE_ITEM");
END_ENTITY

SELECT(SXFDict_AXIS2_PLACEMENT)
	NAME("AXIS2_PLACEMENT");
	SELECTITEM("AXIS2_PLACEMENT_2D");
END_SELECT

ENTITY(SXFDict_AREA_IN_SET)
	NAME("AREA_IN_SET");
	ATTRIBUTE("AREA","PRESENTATION_AREA");
	ATTRIBUTE("IN_SET","PRESENTATION_SET");
END_ENTITY

SELECT(SXFDict_FONT_SELECT)
	NAME("FONT_SELECT");
	SELECTITEM("EXTERNALLY_DEFINED_TEXT_FONT");
END_SELECT

SELECT(SXFDict_DRAUGHTING_CALLOUT_ELEMENT)
	NAME("DRAUGHTING_CALLOUT_ELEMENT");
	SELECTITEM("ANNOTATION_TEXT_OCCURRENCE");
	SELECTITEM("ANNOTATION_SYMBOL_OCCURRENCE");
	SELECTITEM("ANNOTATION_CURVE_OCCURRENCE");
END_SELECT

ENTITY(SXFDict_SYMBOL_STYLE)
	NAME("SYMBOL_STYLE");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("STYLE_OF_SYMBOL","SYMBOL_STYLE_SELECT");
END_ENTITY

ENUMERATION(SXFDict_TRANSITION_CODE)
	NAME("TRANSITION_CODE");
	ENUMITEM("DISCONTINUOUS");
	ENUMITEM("CONTINUOUS");
	ENUMITEM("CONT_SAME_GRADIENT");
	ENUMITEM("CONT_SAME_GRADIENT_SAME_CURVATURE");
END_ENUMERATION

SELECT(SXFDict_MEASURE_VALUE)
	NAME("MEASURE_VALUE");
	SELECTITEM("LENGTH_MEASURE");
	SELECTITEM("PLANE_ANGLE_MEASURE");
	SELECTITEM("RATIO_MEASURE");
	SELECTITEM("PARAMETER_VALUE");
	SELECTITEM("POSITIVE_LENGTH_MEASURE");
	SELECTITEM("POSITIVE_RATIO_MEASURE");
END_SELECT

ENTITY(SXFDict_DRAUGHTING_TITLE)
	NAME("DRAUGHTING_TITLE");
	ATTRIBUTE("ITEMS","SET [ 1 : ? ] OF DRAUGHTING_TITLED_ITEM");
	ATTRIBUTE("LANGUAGE","LABEL");
	ATTRIBUTE("CONTENTS","TEXT");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_CALLOUT_RELATIONSHIP)
	NAME("DRAUGHTING_CALLOUT_RELATIONSHIP");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("DESCRIPTION","TEXT");
	ATTRIBUTE("RELATING_DRAUGHTING_CALLOUT","DRAUGHTING_CALLOUT");
	ATTRIBUTE("RELATED_DRAUGHTING_CALLOUT","DRAUGHTING_CALLOUT");
END_ENTITY

TYPEDEF(SXFDict_BOX_WIDTH,"BOX_WIDTH","POSITIVE_RATIO_MEASURE")

ENTITY(SXFDict_ANNOTATION_SYMBOL_OCCURRENCE)
	NAME("ANNOTATION_SYMBOL_OCCURRENCE");
	SUBTYPE_OF("ANNOTATION_OCCURRENCE");
END_ENTITY

ENUMERATION(SXFDict_PREFERRED_SURFACE_CURVE_REPRESENTATION)
	NAME("PREFERRED_SURFACE_CURVE_REPRESENTATION");
	ENUMITEM("CURVE_3D");
	ENUMITEM("PCURVE_S1");
	ENUMITEM("PCURVE_S2");
END_ENUMERATION

ENTITY(SXFDict_LENGTH_UNIT)
	NAME("LENGTH_UNIT");
	SUBTYPE_OF("NAMED_UNIT");
END_ENTITY

ENTITY(SXFDict_PRESENTATION_STYLE_ASSIGNMENT)
	NAME("PRESENTATION_STYLE_ASSIGNMENT");
	ATTRIBUTE("STYLES","SET [ 1 : ? ] OF PRESENTATION_STYLE_SELECT");
END_ENTITY

ENUMERATION(SXFDict_SI_UNIT_NAME)
	NAME("SI_UNIT_NAME");
	ENUMITEM("METRE");
	ENUMITEM("GRAM");
	ENUMITEM("SECOND");
	ENUMITEM("AMPERE");
	ENUMITEM("KELVIN");
	ENUMITEM("MOLE");
	ENUMITEM("CANDELA");
	ENUMITEM("RADIAN");
	ENUMITEM("STERADIAN");
	ENUMITEM("HERTZ");
	ENUMITEM("NEWTON");
	ENUMITEM("PASCAL");
	ENUMITEM("JOULE");
	ENUMITEM("WATT");
	ENUMITEM("COULOMB");
	ENUMITEM("VOLT");
	ENUMITEM("FARAD");
	ENUMITEM("OHM");
	ENUMITEM("SIEMENS");
	ENUMITEM("WEBER");
	ENUMITEM("TESLA");
	ENUMITEM("HENRY");
	ENUMITEM("DEGREE_CELSIUS");
	ENUMITEM("LUMEN");
	ENUMITEM("LUX");
	ENUMITEM("BECQUEREL");
	ENUMITEM("GRAY");
	ENUMITEM("SIEVERT");
END_ENUMERATION

TYPEDEF(SXFDict_YEAR_NUMBER,"YEAR_NUMBER","INTEGER")

TYPEDEF(SXFDict_DIMENSION_COUNT,"DIMENSION_COUNT","INTEGER")

ENTITY(SXFDict_PRESENTATION_SET)
	NAME("PRESENTATION_SET");
END_ENTITY

ENTITY(SXFDict_LEADER_DIRECTED_DIMENSION)
	NAME("LEADER_DIRECTED_DIMENSION");
	SUBTYPE_OF("LEADER_DIRECTED_CALLOUT");
END_ENTITY

SELECT(SXFDict_HIDING_OR_BLANKING_SELECT)
	NAME("HIDING_OR_BLANKING_SELECT");
	SELECTITEM("ANNOTATION_FILL_AREA");
END_SELECT

SELECT(SXFDict_CURVE_FONT_OR_SCALED_CURVE_FONT_SELECT)
	NAME("CURVE_FONT_OR_SCALED_CURVE_FONT_SELECT");
	SELECTITEM("CURVE_STYLE_FONT_SELECT");
END_SELECT

ENTITY(SXFDict_LEADER_TERMINATOR)
	NAME("LEADER_TERMINATOR");
	SUBTYPE_OF("TERMINATOR_SYMBOL");
END_ENTITY

ENTITY(SXFDict_TRIMMED_CURVE)
	NAME("TRIMMED_CURVE");
	SUBTYPE_OF("BOUNDED_CURVE");
	ATTRIBUTE("BASIS_CURVE","CURVE");
	ATTRIBUTE("TRIM_1","SET [ 1 : 2 ] OF TRIMMING_SELECT");
	ATTRIBUTE("TRIM_2","SET [ 1 : 2 ] OF TRIMMING_SELECT");
	ATTRIBUTE("SENSE_AGREEMENT","BOOLEAN");
	ATTRIBUTE("MASTER_REPRESENTATION","TRIMMING_PREFERENCE");
END_ENTITY

ENTITY(SXFDict_DRAWING_SHEET_REVISION)
	NAME("DRAWING_SHEET_REVISION");
	SUBTYPE_OF("PRESENTATION_AREA");
	ATTRIBUTE("REVISION_IDENTIFIER","IDENTIFIER");
END_ENTITY

ENUMERATION(SXFDict_TEXT_PATH)
	NAME("TEXT_PATH");
	ENUMITEM("LEFT");
	ENUMITEM("RIGHT");
	ENUMITEM("UP");
	ENUMITEM("DOWN");
END_ENUMERATION

SELECT(SXFDict_INVISIBILITY_CONTEXT)
	NAME("INVISIBILITY_CONTEXT");
	SELECTITEM("PRESENTATION_LAYER_USAGE");
	SELECTITEM("PRESENTATION_REPRESENTATION");
	SELECTITEM("PRESENTATION_SET");
END_SELECT

SELECT(SXFDict_GEOMETRIC_SET_SELECT)
	NAME("GEOMETRIC_SET_SELECT");
	SELECTITEM("POINT");
	SELECTITEM("CURVE");
END_SELECT

ENTITY(SXFDict_ANNOTATION_SYMBOL)
	NAME("ANNOTATION_SYMBOL");
	SUBTYPE_OF("MAPPED_ITEM");
END_ENTITY

ENTITY(SXFDict_SYMBOL_REPRESENTATION)
	NAME("SYMBOL_REPRESENTATION");
	SUBTYPE_OF("REPRESENTATION");
END_ENTITY

ENTITY(SXFDict_PRESENTATION_REPRESENTATION)
	NAME("PRESENTATION_REPRESENTATION");
	SUBTYPE_OF("REPRESENTATION");
END_ENTITY

SELECT(SXFDict_TEXT_OR_CHARACTER)
	NAME("TEXT_OR_CHARACTER");
	SELECTITEM("TEXT_LITERAL");
END_SELECT

ENTITY(SXFDict_SI_UNIT)
	NAME("SI_UNIT");
	SUBTYPE_OF("NAMED_UNIT");
	OPTIONAL_ATTRIBUTE("PREFIX","SI_PREFIX");
	ATTRIBUTE("NAME","SI_UNIT_NAME");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_ELEMENTS)
	NAME("DRAUGHTING_ELEMENTS");
	SUBTYPE_OF("DRAUGHTING_CALLOUT");
END_ENTITY

TYPEDEF(SXFDict_BOX_ROTATE_ANGLE,"BOX_ROTATE_ANGLE","PLANE_ANGLE_MEASURE")

ENTITY(SXFDict_DRAWING_DEFINITION)
	NAME("DRAWING_DEFINITION");
	ATTRIBUTE("DRAWING_NUMBER","IDENTIFIER");
	OPTIONAL_ATTRIBUTE("DRAWING_TYPE","LABEL");
END_ENTITY

ENTITY(SXFDict_SYMBOL_REPRESENTATION_MAP)
	NAME("SYMBOL_REPRESENTATION_MAP");
	SUBTYPE_OF("REPRESENTATION_MAP");
END_ENTITY

ENTITY(SXFDict_CURVE_STYLE_FONT)
	NAME("CURVE_STYLE_FONT");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("PATTERN_LIST","LIST [ 1 : ? ] OF CURVE_STYLE_FONT_PATTERN");
END_ENTITY

SELECT(SXFDict_TRIMMING_SELECT)
	NAME("TRIMMING_SELECT");
	SELECTITEM("CARTESIAN_POINT");
	SELECTITEM("PARAMETER_VALUE");
END_SELECT

ENTITY(SXFDict_ANNOTATION_CURVE_OCCURRENCE)
	NAME("ANNOTATION_CURVE_OCCURRENCE");
	SUBTYPE_OF("ANNOTATION_OCCURRENCE");
END_ENTITY

ENTITY(SXFDict_PLACEMENT)
	NAME("PLACEMENT");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("LOCATION","CARTESIAN_POINT");
END_ENTITY

ENTITY(SXFDict_LEADER_CURVE)
	NAME("LEADER_CURVE");
	SUBTYPE_OF("ANNOTATION_CURVE_OCCURRENCE");
END_ENTITY

SELECT(SXFDict_FILL_AREA_STYLE_TILE_SHAPE_SELECT)
	NAME("FILL_AREA_STYLE_TILE_SHAPE_SELECT");
	SELECTITEM("FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE");
END_SELECT

TYPEDEF(SXFDict_BOX_HEIGHT,"BOX_HEIGHT","POSITIVE_RATIO_MEASURE")

ENTITY(SXFDict_GEOMETRIC_REPRESENTATION_CONTEXT)
	NAME("GEOMETRIC_REPRESENTATION_CONTEXT");
	SUBTYPE_OF("REPRESENTATION_CONTEXT");
	ATTRIBUTE("COORDINATE_SPACE_DIMENSION","DIMENSION_COUNT");
END_ENTITY

ENTITY(SXFDict_CURVE_STYLE)
	NAME("CURVE_STYLE");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("CURVE_FONT","CURVE_FONT_OR_SCALED_CURVE_FONT_SELECT");
	ATTRIBUTE("CURVE_WIDTH","SIZE_SELECT");
	ATTRIBUTE("CURVE_COLOUR","COLOUR");
END_ENTITY

SELECT(SXFDict_SOURCE_ITEM)
	NAME("SOURCE_ITEM");
	SELECTITEM("IDENTIFIER");
END_SELECT

SELECT(SXFDict_PRESENTATION_STYLE_SELECT)
	NAME("PRESENTATION_STYLE_SELECT");
	SELECTITEM("CURVE_STYLE");
	SELECTITEM("SYMBOL_STYLE");
	SELECTITEM("FILL_AREA_STYLE");
	SELECTITEM("TEXT_STYLE");
	SELECTITEM("NULL_STYLE");
END_SELECT

SELECT(SXFDict_CONTRACTED_ITEM)
	NAME("CONTRACTED_ITEM");
	SELECTITEM("DRAWING_REVISION");
END_SELECT

ENTITY(SXFDict_LINE)
	NAME("LINE");
	SUBTYPE_OF("CURVE");
	ATTRIBUTE("PNT","CARTESIAN_POINT");
	ATTRIBUTE("DIR","VECTOR");
END_ENTITY

ENTITY(SXFDict_INVISIBILITY)
	NAME("INVISIBILITY");
	ATTRIBUTE("INVISIBLE_ITEMS","SET [ 1 : ? ] OF INVISIBLE_ITEM");
END_ENTITY

ENTITY(SXFDict_STYLED_ITEM)
	NAME("STYLED_ITEM");
	SUBTYPE_OF("REPRESENTATION_ITEM");
	ATTRIBUTE("STYLES","SET [ 1 : ? ] OF PRESENTATION_STYLE_ASSIGNMENT");
	ATTRIBUTE("ITEM","REPRESENTATION_ITEM");
END_ENTITY

ENTITY(SXFDict_PRE_DEFINED_CURVE_FONT)
	NAME("PRE_DEFINED_CURVE_FONT");
	SUBTYPE_OF("PRE_DEFINED_ITEM");
END_ENTITY

ENTITY(SXFDict_FILL_AREA_STYLE_TILES)
	NAME("FILL_AREA_STYLE_TILES");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("TILING_PATTERN","TWO_DIRECTION_REPEAT_FACTOR");
	ATTRIBUTE("TILES","SET [ 1 : ? ] OF FILL_AREA_STYLE_TILE_SHAPE_SELECT");
	ATTRIBUTE("TILING_SCALE","POSITIVE_RATIO_MEASURE");
END_ENTITY

ENTITY(SXFDict_TERMINATOR_SYMBOL)
	NAME("TERMINATOR_SYMBOL");
	SUBTYPE_OF("ANNOTATION_SYMBOL_OCCURRENCE");
	ATTRIBUTE("ANNOTATED_CURVE","ANNOTATION_CURVE_OCCURRENCE");
END_ENTITY

ENTITY(SXFDict_PRE_DEFINED_COLOUR)
	NAME("PRE_DEFINED_COLOUR");
	SUBTYPE_OF("PRE_DEFINED_ITEM");
	SUBTYPE_OF("COLOUR");
END_ENTITY

ENTITY(SXFDict_DERIVED_UNIT_ELEMENT)
	NAME("DERIVED_UNIT_ELEMENT");
	ATTRIBUTE("UNIT","NAMED_UNIT");
	ATTRIBUTE("EXPONENT","REAL");
END_ENTITY

ENTITY(SXFDict_EXTERNALLY_DEFINED_HATCH_STYLE)
	NAME("EXTERNALLY_DEFINED_HATCH_STYLE");
	SUBTYPE_OF("EXTERNALLY_DEFINED_ITEM");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
END_ENTITY

TYPEDEF(SXFDict_LABEL,"LABEL","STRING")

ENTITY(SXFDict_DRAUGHTING_DRAWING_REVISION)
	NAME("DRAUGHTING_DRAWING_REVISION");
	SUBTYPE_OF("DRAWING_REVISION");
END_ENTITY

ENTITY(SXFDict_VECTOR)
	NAME("VECTOR");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("ORIENTATION","DIRECTION");
	ATTRIBUTE("MAGNITUDE","LENGTH_MEASURE");
END_ENTITY

ENUMERATION(SXFDict_NULL_STYLE)
	NAME("NULL_STYLE");
	ENUMITEM("NULL");
END_ENUMERATION

ENTITY(SXFDict_PRESENTATION_SIZE)
	NAME("PRESENTATION_SIZE");
	ATTRIBUTE("UNIT","PRESENTATION_SIZE_ASSIGNMENT_SELECT");
	ATTRIBUTE("SIZE","PLANAR_BOX");
END_ENTITY

ENTITY(SXFDict_EXTERNALLY_DEFINED_SYMBOL)
	NAME("EXTERNALLY_DEFINED_SYMBOL");
	SUBTYPE_OF("EXTERNALLY_DEFINED_ITEM");
END_ENTITY

ENTITY(SXFDict_PRESENTATION_LAYER_USAGE)
	NAME("PRESENTATION_LAYER_USAGE");
	ATTRIBUTE("ASSIGNMENT","PRESENTATION_LAYER_ASSIGNMENT");
	ATTRIBUTE("PRESENTATION","PRESENTATION_REPRESENTATION");
END_ENTITY

SELECT(SXFDict_SYMBOL_STYLE_SELECT)
	NAME("SYMBOL_STYLE_SELECT");
	SELECTITEM("SYMBOL_COLOUR");
END_SELECT

ENTITY(SXFDict_LINEAR_DIMENSION)
	NAME("LINEAR_DIMENSION");
	SUBTYPE_OF("DIMENSION_CURVE_DIRECTED_CALLOUT");
END_ENTITY

ENTITY(SXFDict_TEXT_STYLE_FOR_DEFINED_FONT)
	NAME("TEXT_STYLE_FOR_DEFINED_FONT");
	ATTRIBUTE("TEXT_COLOUR","COLOUR");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_CALLOUT)
	NAME("DRAUGHTING_CALLOUT");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("CONTENTS","SET [ 1 : ? ] OF DRAUGHTING_CALLOUT_ELEMENT");
END_ENTITY

ENUMERATION(SXFDict_AHEAD_OR_BEHIND)
	NAME("AHEAD_OR_BEHIND");
	ENUMITEM("AHEAD");
	ENUMITEM("BEHIND");
END_ENUMERATION

SELECT(SXFDict_CURVE_STYLE_FONT_SELECT)
	NAME("CURVE_STYLE_FONT_SELECT");
	SELECTITEM("CURVE_STYLE_FONT");
	SELECTITEM("PRE_DEFINED_CURVE_FONT");
END_SELECT

ENTITY(SXFDict_FILL_AREA_STYLE_HATCHING)
	NAME("FILL_AREA_STYLE_HATCHING");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("HATCH_LINE_APPEARANCE","CURVE_STYLE");
	ATTRIBUTE("START_OF_NEXT_HATCH_LINE","ONE_DIRECTION_REPEAT_FACTOR");
	ATTRIBUTE("POINT_OF_REFERENCE_HATCH_LINE","CARTESIAN_POINT");
	ATTRIBUTE("PATTERN_START","CARTESIAN_POINT");
	ATTRIBUTE("HATCH_LINE_ANGLE","PLANE_ANGLE_MEASURE");
END_ENTITY

TYPEDEF(SXFDict_BOX_SLANT_ANGLE,"BOX_SLANT_ANGLE","PLANE_ANGLE_MEASURE")

ENTITY(SXFDict_DRAWING_SHEET_REVISION_USAGE)
	NAME("DRAWING_SHEET_REVISION_USAGE");
	SUBTYPE_OF("AREA_IN_SET");
	ATTRIBUTE("SHEET_NUMBER","IDENTIFIER");
END_ENTITY

ENTITY(SXFDict_ANNOTATION_TEXT_OCCURRENCE)
	NAME("ANNOTATION_TEXT_OCCURRENCE");
	SUBTYPE_OF("ANNOTATION_OCCURRENCE");
END_ENTITY

ENTITY(SXFDict_TEXT_STYLE_WITH_BOX_CHARACTERISTICS)
	NAME("TEXT_STYLE_WITH_BOX_CHARACTERISTICS");
	SUBTYPE_OF("TEXT_STYLE");
	ATTRIBUTE("CHARACTERISTICS","SET [ 1 : 4 ] OF BOX_CHARACTERISTIC_SELECT");
END_ENTITY

ENTITY(SXFDict_REPRESENTATION_MAP)
	NAME("REPRESENTATION_MAP");
	ATTRIBUTE("MAPPING_ORIGIN","REPRESENTATION_ITEM");
	ATTRIBUTE("MAPPED_REPRESENTATION","REPRESENTATION");
END_ENTITY

ENTITY(SXFDict_DIMENSION_CALLOUT_RELATIONSHIP)
	NAME("DIMENSION_CALLOUT_RELATIONSHIP");
	SUBTYPE_OF("DRAUGHTING_CALLOUT_RELATIONSHIP");
END_ENTITY

ENTITY(SXFDict_AXIS2_PLACEMENT_2D)
	NAME("AXIS2_PLACEMENT_2D");
	SUBTYPE_OF("PLACEMENT");
	OPTIONAL_ATTRIBUTE("REF_DIRECTION","DIRECTION");
END_ENTITY

SELECT(SXFDict_CURVE_OR_RENDER)
	NAME("CURVE_OR_RENDER");
	SELECTITEM("CURVE_STYLE");
END_SELECT

ENUMERATION(SXFDict_B_SPLINE_SURFACE_FORM)
	NAME("B_SPLINE_SURFACE_FORM");
	ENUMITEM("PLANE_SURF");
	ENUMITEM("CYLINDRICAL_SURF");
	ENUMITEM("CONICAL_SURF");
	ENUMITEM("SPHERICAL_SURF");
	ENUMITEM("TOROIDAL_SURF");
	ENUMITEM("SURF_OF_REVOLUTION");
	ENUMITEM("RULED_SURF");
	ENUMITEM("GENERALISED_CONE");
	ENUMITEM("QUADRIC_SURF");
	ENUMITEM("SURF_OF_LINEAR_EXTRUSION");
	ENUMITEM("UNSPECIFIED");
END_ENUMERATION

ENTITY(SXFDict_EXTERNALLY_DEFINED_TEXT_FONT)
	NAME("EXTERNALLY_DEFINED_TEXT_FONT");
	SUBTYPE_OF("EXTERNALLY_DEFINED_ITEM");
END_ENTITY

ENTITY(SXFDict_CONIC)
	NAME("CONIC");
	SUBTYPE_OF("CURVE");
	ATTRIBUTE("POSITION","AXIS2_PLACEMENT");
END_ENTITY

SELECT(SXFDict_CHARACTER_STYLE_SELECT)
	NAME("CHARACTER_STYLE_SELECT");
	SELECTITEM("TEXT_STYLE_FOR_DEFINED_FONT");
END_SELECT

ENTITY(SXFDict_TEXT_STYLE_WITH_SPACING)
	NAME("TEXT_STYLE_WITH_SPACING");
	SUBTYPE_OF("TEXT_STYLE");
	ATTRIBUTE("CHARACTER_SPACING","CHARACTER_SPACING_SELECT");
END_ENTITY

SELECT(SXFDict_PRESENTATION_SIZE_ASSIGNMENT_SELECT)
	NAME("PRESENTATION_SIZE_ASSIGNMENT_SELECT");
	SELECTITEM("PRESENTATION_AREA");
	SELECTITEM("AREA_IN_SET");
END_SELECT

ENTITY(SXFDict_ONE_DIRECTION_REPEAT_FACTOR)
	NAME("ONE_DIRECTION_REPEAT_FACTOR");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("REPEAT_FACTOR","VECTOR");
END_ENTITY

ENTITY(SXFDict_ELLIPSE)
	NAME("ELLIPSE");
	SUBTYPE_OF("CONIC");
	ATTRIBUTE("SEMI_AXIS_1","POSITIVE_LENGTH_MEASURE");
	ATTRIBUTE("SEMI_AXIS_2","POSITIVE_LENGTH_MEASURE");
END_ENTITY

SELECT(SXFDict_MARKER_SELECT)
	NAME("MARKER_SELECT");
	SELECTITEM("PRE_DEFINED_MARKER");
END_SELECT

ENTITY(SXFDict_LENGTH_MEASURE_WITH_UNIT)
	NAME("LENGTH_MEASURE_WITH_UNIT");
	SUBTYPE_OF("MEASURE_WITH_UNIT");
END_ENTITY

ENUMERATION(SXFDict_B_SPLINE_CURVE_FORM)
	NAME("B_SPLINE_CURVE_FORM");
	ENUMITEM("POLYLINE_FORM");
	ENUMITEM("CIRCULAR_ARC");
	ENUMITEM("ELLIPTIC_ARC");
	ENUMITEM("PARABOLIC_ARC");
	ENUMITEM("HYPERBOLIC_ARC");
	ENUMITEM("UNSPECIFIED");
END_ENUMERATION

SELECT(SXFDict_INVISIBLE_ITEM)
	NAME("INVISIBLE_ITEM");
	SELECTITEM("STYLED_ITEM");
	SELECTITEM("PRESENTATION_LAYER_ASSIGNMENT");
	SELECTITEM("PRESENTATION_REPRESENTATION");
END_SELECT

ENTITY(SXFDict_DIRECTION)
	NAME("DIRECTION");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("DIRECTION_RATIOS","LIST [ 2 : 3 ] OF REAL");
END_ENTITY

SELECT(SXFDict_FILL_STYLE_SELECT)
	NAME("FILL_STYLE_SELECT");
	SELECTITEM("FILL_AREA_STYLE_COLOUR");
	SELECTITEM("FILL_AREA_STYLE_TILES");
	SELECTITEM("EXTERNALLY_DEFINED_HATCH_STYLE");
	SELECTITEM("FILL_AREA_STYLE_HATCHING");
END_SELECT

ENTITY(SXFDict_COLOUR)
	NAME("COLOUR");
END_ENTITY

ENTITY(SXFDict_REPRESENTATION)
	NAME("REPRESENTATION");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("ITEMS","SET [ 1 : ? ] OF REPRESENTATION_ITEM");
	ATTRIBUTE("CONTEXT_OF_ITEMS","REPRESENTATION_CONTEXT");
END_ENTITY

ENTITY(SXFDict_DRAWING_REVISION)
	NAME("DRAWING_REVISION");
	SUBTYPE_OF("PRESENTATION_SET");
	ATTRIBUTE("REVISION_IDENTIFIER","IDENTIFIER");
	ATTRIBUTE("DRAWING_IDENTIFIER","DRAWING_DEFINITION");
	OPTIONAL_ATTRIBUTE("INTENDED_SCALE","TEXT");
END_ENTITY

ENTITY(SXFDict_ANNOTATION_FILL_AREA_OCCURRENCE)
	NAME("ANNOTATION_FILL_AREA_OCCURRENCE");
	SUBTYPE_OF("ANNOTATION_OCCURRENCE");
	ATTRIBUTE("FILL_STYLE_TARGET","POINT");
END_ENTITY

ENTITY(SXFDict_TEXT_STYLE)
	NAME("TEXT_STYLE");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("CHARACTER_APPEARANCE","CHARACTER_STYLE_SELECT");
END_ENTITY

ENTITY(SXFDict_B_SPLINE_CURVE)
	NAME("B_SPLINE_CURVE");
	SUBTYPE_OF("BOUNDED_CURVE");
	ATTRIBUTE("DEGREE","INTEGER");
	ATTRIBUTE("CONTROL_POINTS_LIST","LIST [ 2 : ? ] OF CARTESIAN_POINT");
	ATTRIBUTE("CURVE_FORM","B_SPLINE_CURVE_FORM");
	ATTRIBUTE("CLOSED_CURVE","LOGICAL");
	ATTRIBUTE("SELF_INTERSECT","LOGICAL");
END_ENTITY

ENTITY(SXFDict_FILL_AREA_STYLE_COLOUR)
	NAME("FILL_AREA_STYLE_COLOUR");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("FILL_COLOUR","COLOUR");
END_ENTITY

ENTITY(SXFDict_CARTESIAN_POINT)
	NAME("CARTESIAN_POINT");
	SUBTYPE_OF("POINT");
	ATTRIBUTE("COORDINATES","LIST [ 1 : 3 ] OF LENGTH_MEASURE");
END_ENTITY

ENTITY(SXFDict_ANNOTATION_FILL_AREA)
	NAME("ANNOTATION_FILL_AREA");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("BOUNDARIES","SET [ 1 : ? ] OF CURVE");
END_ENTITY

ENTITY(SXFDict_ANNOTATION_OCCURRENCE)
	NAME("ANNOTATION_OCCURRENCE");
	SUBTYPE_OF("STYLED_ITEM");
END_ENTITY

SELECT(SXFDict_UNIT)
	NAME("UNIT");
	SELECTITEM("NAMED_UNIT");
	SELECTITEM("DERIVED_UNIT");
END_SELECT

SELECT(SXFDict_PRESENTATION_REPRESENTATION_SELECT)
	NAME("PRESENTATION_REPRESENTATION_SELECT");
	SELECTITEM("PRESENTATION_REPRESENTATION");
	SELECTITEM("PRESENTATION_SET");
END_SELECT

ENTITY(SXFDict_DIMENSION_CURVE_TERMINATOR)
	NAME("DIMENSION_CURVE_TERMINATOR");
	SUBTYPE_OF("TERMINATOR_SYMBOL");
	ATTRIBUTE("ROLE","DIMENSION_EXTENT_USAGE");
END_ENTITY

TYPEDEF(SXFDict_POSITIVE_LENGTH_MEASURE,"POSITIVE_LENGTH_MEASURE","LENGTH_MEASURE")

SELECT(SXFDict_BOX_CHARACTERISTIC_SELECT)
	NAME("BOX_CHARACTERISTIC_SELECT");
	SELECTITEM("BOX_HEIGHT");
	SELECTITEM("BOX_WIDTH");
	SELECTITEM("BOX_SLANT_ANGLE");
	SELECTITEM("BOX_ROTATE_ANGLE");
END_SELECT

ENTITY(SXFDict_ANNOTATION_SUBFIGURE_OCCURRENCE)
	NAME("ANNOTATION_SUBFIGURE_OCCURRENCE");
	SUBTYPE_OF("ANNOTATION_SYMBOL_OCCURRENCE");
END_ENTITY

ENTITY(SXFDict_DIMENSIONAL_EXPONENTS)
	NAME("DIMENSIONAL_EXPONENTS");
	ATTRIBUTE("LENGTH_EXPONENT","REAL");
	ATTRIBUTE("MASS_EXPONENT","REAL");
	ATTRIBUTE("TIME_EXPONENT","REAL");
	ATTRIBUTE("ELECTRIC_CURRENT_EXPONENT","REAL");
	ATTRIBUTE("THERMODYNAMIC_TEMPERATURE_EXPONENT","REAL");
	ATTRIBUTE("AMOUNT_OF_SUBSTANCE_EXPONENT","REAL");
	ATTRIBUTE("LUMINOUS_INTENSITY_EXPONENT","REAL");
END_ENTITY

ENTITY(SXFDict_PLANE_ANGLE_UNIT)
	NAME("PLANE_ANGLE_UNIT");
	SUBTYPE_OF("NAMED_UNIT");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_ANNOTATION_OCCURRENCE)
	NAME("DRAUGHTING_ANNOTATION_OCCURRENCE");
	SUBTYPE_OF("ANNOTATION_OCCURRENCE");
END_ENTITY

ENTITY(SXFDict_CLOTHOID)
	NAME("CLOTHOID");
	SUBTYPE_OF("CURVE");
	ATTRIBUTE("POSITION","AXIS2_PLACEMENT");
	ATTRIBUTE("CLOTHOID_CONSTANT","LENGTH_MEASURE");
END_ENTITY

ENTITY(SXFDict_CURVE_DIMENSION)
	NAME("CURVE_DIMENSION");
	SUBTYPE_OF("DIMENSION_CURVE_DIRECTED_CALLOUT");
END_ENTITY

ENTITY(SXFDict_ANGULAR_DIMENSION)
	NAME("ANGULAR_DIMENSION");
	SUBTYPE_OF("DIMENSION_CURVE_DIRECTED_CALLOUT");
END_ENTITY

TYPEDEF(SXFDict_TEXT_ALIGNMENT,"TEXT_ALIGNMENT","LABEL")

ENTITY(SXFDict_PLANAR_EXTENT)
	NAME("PLANAR_EXTENT");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("SIZE_IN_X","LENGTH_MEASURE");
	ATTRIBUTE("SIZE_IN_Y","LENGTH_MEASURE");
END_ENTITY

TYPEDEF(SXFDict_POSITIVE_RATIO_MEASURE,"POSITIVE_RATIO_MEASURE","RATIO_MEASURE")

ENTITY(SXFDict_FILL_AREA_STYLE)
	NAME("FILL_AREA_STYLE");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("FILL_STYLES","SET [ 1 : ? ] OF FILL_STYLE_SELECT");
END_ENTITY

ENTITY(SXFDict_BEZIER_CURVE)
	NAME("BEZIER_CURVE");
	SUBTYPE_OF("B_SPLINE_CURVE");
END_ENTITY

ENTITY(SXFDict_DIAMETER_DIMENSION)
	NAME("DIAMETER_DIMENSION");
	SUBTYPE_OF("DIMENSION_CURVE_DIRECTED_CALLOUT");
END_ENTITY

ENTITY(SXFDict_DIMENSION_CURVE_DIRECTED_CALLOUT)
	NAME("DIMENSION_CURVE_DIRECTED_CALLOUT");
	SUBTYPE_OF("DRAUGHTING_CALLOUT");
END_ENTITY

TYPEDEF(SXFDict_PLANE_ANGLE_MEASURE,"PLANE_ANGLE_MEASURE","REAL")

TYPEDEF(SXFDict_PRESENTABLE_TEXT,"PRESENTABLE_TEXT","STRING")

ENTITY(SXFDict_PRE_DEFINED_TEXT_FONT)
	NAME("PRE_DEFINED_TEXT_FONT");
	SUBTYPE_OF("PRE_DEFINED_ITEM");
END_ENTITY

ENTITY(SXFDict_CIRCLE)
	NAME("CIRCLE");
	SUBTYPE_OF("CONIC");
	ATTRIBUTE("RADIUS","POSITIVE_LENGTH_MEASURE");
END_ENTITY

ENTITY(SXFDict_COLOUR_SPECIFICATION)
	NAME("COLOUR_SPECIFICATION");
	SUBTYPE_OF("COLOUR");
	ATTRIBUTE("NAME","LABEL");
END_ENTITY

ENTITY(SXFDict_PROJECTION_CURVE)
	NAME("PROJECTION_CURVE");
	SUBTYPE_OF("ANNOTATION_CURVE_OCCURRENCE");
END_ENTITY

SELECT(SXFDict_DRAUGHTING_ORGANIZATION_ITEM)
	NAME("DRAUGHTING_ORGANIZATION_ITEM");
	SELECTITEM("DRAWING_REVISION");
	SELECTITEM("DRAWING_SHEET_REVISION");
END_SELECT

ENTITY(SXFDict_COMPOSITE_CURVE_SEGMENT)
	NAME("COMPOSITE_CURVE_SEGMENT");
	ATTRIBUTE("TRANSITION","TRANSITION_CODE");
	ATTRIBUTE("SAME_SENSE","BOOLEAN");
	ATTRIBUTE("PARENT_CURVE","CURVE");
END_ENTITY

TYPEDEF(SXFDict_IDENTIFIER,"IDENTIFIER","STRING")

TYPEDEF(SXFDict_LENGTH_MEASURE,"LENGTH_MEASURE","REAL")

ENTITY(SXFDict_TWO_DIRECTION_REPEAT_FACTOR)
	NAME("TWO_DIRECTION_REPEAT_FACTOR");
	SUBTYPE_OF("ONE_DIRECTION_REPEAT_FACTOR");
	ATTRIBUTE("SECOND_REPEAT_FACTOR","VECTOR");
END_ENTITY

TYPEDEF(SXFDict_TEXT,"TEXT","STRING")

ENTITY(SXFDict_PRE_DEFINED_MARKER)
	NAME("PRE_DEFINED_MARKER");
	SUBTYPE_OF("PRE_DEFINED_ITEM");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_PRE_DEFINED_CURVE_FONT)
	NAME("DRAUGHTING_PRE_DEFINED_CURVE_FONT");
	SUBTYPE_OF("PRE_DEFINED_CURVE_FONT");
END_ENTITY

ENTITY(SXFDict_DIMENSION_CURVE)
	NAME("DIMENSION_CURVE");
	SUBTYPE_OF("ANNOTATION_CURVE_OCCURRENCE");
END_ENTITY

ENTITY(SXFDict_COLOUR_RGB)
	NAME("COLOUR_RGB");
	SUBTYPE_OF("COLOUR_SPECIFICATION");
	ATTRIBUTE("RED","REAL");
	ATTRIBUTE("GREEN","REAL");
	ATTRIBUTE("BLUE","REAL");
END_ENTITY

ENTITY(SXFDict_REPRESENTATION_CONTEXT)
	NAME("REPRESENTATION_CONTEXT");
	ATTRIBUTE("CONTEXT_IDENTIFIER","IDENTIFIER");
	ATTRIBUTE("CONTEXT_TYPE","TEXT");
END_ENTITY

ENTITY(SXFDict_PRESENTATION_AREA)
	NAME("PRESENTATION_AREA");
	SUBTYPE_OF("PRESENTATION_REPRESENTATION");
END_ENTITY

ENUMERATION(SXFDict_KNOT_TYPE)
	NAME("KNOT_TYPE");
	ENUMITEM("UNIFORM_KNOTS");
	ENUMITEM("UNSPECIFIED");
	ENUMITEM("QUASI_UNIFORM_KNOTS");
	ENUMITEM("PIECEWISE_BEZIER_KNOTS");
END_ENUMERATION

ENTITY(SXFDict_DERIVED_UNIT)
	NAME("DERIVED_UNIT");
	ATTRIBUTE("ELEMENTS","SET [ 1 : ? ] OF DERIVED_UNIT_ELEMENT");
END_ENTITY

SELECT(SXFDict_DRAUGHTING_GROUP_ELEMENT)
	NAME("DRAUGHTING_GROUP_ELEMENT");
	SELECTITEM("ANNOTATION_OCCURRENCE");
	SELECTITEM("POINT");
	SELECTITEM("CURVE");
END_SELECT

ENTITY(SXFDict_STRUCTURED_DIMENSION_CALLOUT)
	NAME("STRUCTURED_DIMENSION_CALLOUT");
	SUBTYPE_OF("DRAUGHTING_CALLOUT");
END_ENTITY

ENUMERATION(SXFDict_TRIMMING_PREFERENCE)
	NAME("TRIMMING_PREFERENCE");
	ENUMITEM("CARTESIAN");
	ENUMITEM("PARAMETER");
	ENUMITEM("UNSPECIFIED");
END_ENUMERATION

ENTITY(SXFDict_RADIUS_DIMENSION)
	NAME("RADIUS_DIMENSION");
	SUBTYPE_OF("DIMENSION_CURVE_DIRECTED_CALLOUT");
END_ENTITY

ENTITY(SXFDict_TEXT_LITERAL_WITH_EXTENT)
	NAME("TEXT_LITERAL_WITH_EXTENT");
	SUBTYPE_OF("TEXT_LITERAL");
	ATTRIBUTE("EXTENT","PLANAR_EXTENT");
END_ENTITY

ENTITY(SXFDict_GEOMETRIC_REPRESENTATION_ITEM)
	NAME("GEOMETRIC_REPRESENTATION_ITEM");
	SUBTYPE_OF("REPRESENTATION_ITEM");
END_ENTITY

ENTITY(SXFDict_PRESENTATION_LAYER_ASSIGNMENT)
	NAME("PRESENTATION_LAYER_ASSIGNMENT");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("DESCRIPTION","TEXT");
	ATTRIBUTE("ASSIGNED_ITEMS","SET [ 1 : ? ] OF LAYERED_ITEM");
END_ENTITY

SELECT(SXFDict_SPECIFIED_ITEM)
	NAME("SPECIFIED_ITEM");
	SELECTITEM("DRAWING_REVISION");
END_SELECT

ENTITY(SXFDict_DEFINED_SYMBOL)
	NAME("DEFINED_SYMBOL");
	SUBTYPE_OF("GEOMETRIC_REPRESENTATION_ITEM");
	ATTRIBUTE("DEFINITION","DEFINED_SYMBOL_SELECT");
	ATTRIBUTE("TARGET","SYMBOL_TARGET");
END_ENTITY

ENTITY(SXFDict_CURVE_STYLE_FONT_PATTERN)
	NAME("CURVE_STYLE_FONT_PATTERN");
	ATTRIBUTE("VISIBLE_SEGMENT_LENGTH","POSITIVE_LENGTH_MEASURE");
	ATTRIBUTE("INVISIBLE_SEGMENT_LENGTH","POSITIVE_LENGTH_MEASURE");
END_ENTITY

SELECT(SXFDict_LAYERED_ITEM)
	NAME("LAYERED_ITEM");
	SELECTITEM("PRESENTATION_REPRESENTATION");
	SELECTITEM("REPRESENTATION_ITEM");
END_SELECT

//	ADD(S)	Ver3.0対応	K.Naono	04.01.30
TYPEDEF(SXFDict_DAY_IN_MONTH_NUMBER,"DAY_IN_MONTH_NUMBER","INTEGER")
TYPEDEF(SXFDict_MONTH_IN_YEAR_NUMBER,"MONTH_IN_YEAR_NUMBER","INTEGER")

SELECT(SXFDict_DATE_TIME_SELECT)
	NAME("DATE_TIME_SELECT");
	SELECTITEM("DATE");
END_SELECT

ENTITY(SXFDict_CONTRACT_TYPE)
	NAME("CONTRACT_TYPE");
	ATTRIBUTE("DESCRIPTION","LABEL");
END_ENTITY

ENTITY(SXFDict_CONTRACT)
	NAME("CONTRACT");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("PURPOSE","TEXT");
	ATTRIBUTE("KIND","CONTRACT_TYPE");
END_ENTITY

ENTITY(SXFDict_CONTRACT_ASSIGNMENT)
	NAME("CONTRACT_ASSIGNMENT");
	ATTRIBUTE("ASSIGNED_CONTRACT","CONTRACT");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_CONTRACT_ASSIGNMENT)
	NAME("DRAUGHTING_CONTRACT_ASSIGNMENT");
	SUBTYPE_OF("CONTRACT_ASSIGNMENT");
	ATTRIBUTE("ITEMS","SET [ 1 : ? ] OF CONTRACTED_ITEM");
END_ENTITY

ENTITY(SXFDict_DATE)
	NAME("DATE");
	ATTRIBUTE("YEAR_COMPONENT","YEAR_NUMBER");
END_ENTITY

ENTITY(SXFDict_CALENDAR_DATE)
	NAME("CALENDAR_DATE");
	SUBTYPE_OF("DATE");
	ATTRIBUTE("DAY_COMPONENT","DAY_IN_MONTH_NUMBER");
	ATTRIBUTE("MONTH_COMPONENT","MONTH_IN_YEAR_NUMBER");
END_ENTITY

ENTITY(SXFDict_APPROVAL_STATUS)
	NAME("APPROVAL_STATUS");
	ATTRIBUTE("NAME","LABEL");
END_ENTITY

ENTITY(SXFDict_APPROVAL)
	NAME("APPROVAL");
	ATTRIBUTE("STATUS","APPROVAL_STATUS");
	ATTRIBUTE("LEVEL","LABEL");
END_ENTITY

ENTITY(SXFDict_APPROVAL_DATE_TIME)
	NAME("APPROVAL_DATE_TIME");
	ATTRIBUTE("DATE_TIME","DATE_TIME_SELECT");
	ATTRIBUTE("DATED_APPROVAL","APPROVAL");
END_ENTITY

ENTITY(SXFDict_APPROVAL_ASSIGNMENT)
	NAME("APPROVAL_ASSIGNMENT");
	ATTRIBUTE("ASSIGNED_APPROVAL","APPROVAL");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_APPROVAL_ASSIGNMENT)
	NAME("DRAUGHTING_APPROVAL_ASSIGNMENT");
	SUBTYPE_OF("APPROVAL_ASSIGNMENT");
	ATTRIBUTE("APPROVED_ITEMS","SET [ 1 : ? ] OF APPROVED_ITEM");
END_ENTITY

ENTITY(SXFDict_ORGANIZATION)
	NAME("ORGANIZATION");
	OPTIONAL_ATTRIBUTE("ID","IDENTIFIER");
	ATTRIBUTE("NAME","LABEL");
	ATTRIBUTE("DESCRIPTION","TEXT");
END_ENTITY

ENTITY(SXFDict_ORGANIZATION_ROLE)
	NAME("ORGANIZATION_ROLE");
	ATTRIBUTE("NAME","LABEL");
END_ENTITY

ENTITY(SXFDict_ORGANIZATION_ASSIGNMENT)
	NAME("ORGANIZATION_ASSIGNMENT");
	ATTRIBUTE("ASSIGNED_ORGANIZATION","ORGANIZATION");
	ATTRIBUTE("ROLE","ORGANIZATION_ROLE");
END_ENTITY

ENTITY(SXFDict_DRAUGHTING_ORGANIZATION_ASSIGNMENT)
	NAME("DRAUGHTING_ORGANIZATION_ASSIGNMENT");
	SUBTYPE_OF("ORGANIZATION_ASSIGNMENT");
	ATTRIBUTE("ASSIGNED_ITEMS", "SET [ 1 : ? ] OF DRAUGHTING_ORGANIZATION_ITEM");
END_ENTITY
//	ADD(E)	Ver3.0対応	K.Naono	04.01.30

REGISTER_TYPE
	ADDATTRTYPE(SXFDict_FILL_AREA_STYLE_TILE_SYMBOL_WITH_STYLE);
	ADDATTRTYPE(SXFDict_MEASURE_WITH_UNIT);
	ADDATTRTYPE(SXFDict_PARAMETER_VALUE);
	ADDATTRTYPE(SXFDict_COMPOSITE_CURVE);
	ADDATTRTYPE(SXFDict_CENTRAL_OR_PARALLEL);
	ADDATTRTYPE(SXFDict_DRAUGHTING_PRE_DEFINED_COLOUR);
	ADDATTRTYPE(SXFDict_SYMBOL_COLOUR);
	ADDATTRTYPE(SXFDict_TEXT_LITERAL);
	ADDATTRTYPE(SXFDict_CURVE);
	ADDATTRTYPE(SXFDict_STYLE_CONTEXT_SELECT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_SUBFIGURE_REPRESENTATION);
	ADDATTRTYPE(SXFDict_TEXT_DELINEATION);
	ADDATTRTYPE(SXFDict_RATIO_MEASURE);
	ADDATTRTYPE(SXFDict_PLANAR_BOX);
	ADDATTRTYPE(SXFDict_EXTERNALLY_DEFINED_ITEM);
	ADDATTRTYPE(SXFDict_NAMED_UNIT);
	ADDATTRTYPE(SXFDict_VECTOR_OR_DIRECTION);
	ADDATTRTYPE(SXFDict_SYMBOL_TARGET);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_ITEM);
	ADDATTRTYPE(SXFDict_ANGLE_RELATOR);
	ADDATTRTYPE(SXFDict_CLASSIFIED_ITEM);
	ADDATTRTYPE(SXFDict_REPRESENTATION_ITEM);
	ADDATTRTYPE(SXFDict_POINT);
	ADDATTRTYPE(SXFDict_SIZE_SELECT);
	ADDATTRTYPE(SXFDict_DIMENSION_EXTENT_USAGE);
	ADDATTRTYPE(SXFDict_CHARACTER_SPACING_SELECT);
	ADDATTRTYPE(SXFDict_POLYLINE);
	ADDATTRTYPE(SXFDict_LEADER_DIRECTED_CALLOUT);
	ADDATTRTYPE(SXFDict_MAPPED_ITEM);
	ADDATTRTYPE(SXFDict_DEFINED_SYMBOL_SELECT);
	ADDATTRTYPE(SXFDict_DIMENSION_PAIR);
	ADDATTRTYPE(SXFDict_BOUNDED_CURVE);
	ADDATTRTYPE(SXFDict_CURVE_OR_ANNOTATION_CURVE_OCCURRENCE);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_SYMBOL);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_TERMINATOR_SYMBOL);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_POINT_MARKER_SYMBOL);
	ADDATTRTYPE(SXFDict_GLOBAL_UNIT_ASSIGNED_CONTEXT);
	ADDATTRTYPE(SXFDict_SI_PREFIX);
	ADDATTRTYPE(SXFDict_DRAUGHTING_TITLED_ITEM);
	ADDATTRTYPE(SXFDict_APPROVED_ITEM);
	ADDATTRTYPE(SXFDict_EXTERNAL_SOURCE);
	ADDATTRTYPE(SXFDict_AXIS2_PLACEMENT);
	ADDATTRTYPE(SXFDict_AREA_IN_SET);
	ADDATTRTYPE(SXFDict_FONT_SELECT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_CALLOUT_ELEMENT);
	ADDATTRTYPE(SXFDict_SYMBOL_STYLE);
	ADDATTRTYPE(SXFDict_TRANSITION_CODE);
	ADDATTRTYPE(SXFDict_MEASURE_VALUE);
	ADDATTRTYPE(SXFDict_DRAUGHTING_TITLE);
	ADDATTRTYPE(SXFDict_DRAUGHTING_CALLOUT_RELATIONSHIP);
	ADDATTRTYPE(SXFDict_BOX_WIDTH);
	ADDATTRTYPE(SXFDict_ANNOTATION_SYMBOL_OCCURRENCE);
	ADDATTRTYPE(SXFDict_PREFERRED_SURFACE_CURVE_REPRESENTATION);
	ADDATTRTYPE(SXFDict_LENGTH_UNIT);
	ADDATTRTYPE(SXFDict_PRESENTATION_STYLE_ASSIGNMENT);
	ADDATTRTYPE(SXFDict_SI_UNIT_NAME);
	ADDATTRTYPE(SXFDict_YEAR_NUMBER);
	ADDATTRTYPE(SXFDict_DIMENSION_COUNT);
	ADDATTRTYPE(SXFDict_PRESENTATION_SET);
	ADDATTRTYPE(SXFDict_LEADER_DIRECTED_DIMENSION);
	ADDATTRTYPE(SXFDict_HIDING_OR_BLANKING_SELECT);
	ADDATTRTYPE(SXFDict_CURVE_FONT_OR_SCALED_CURVE_FONT_SELECT);
	ADDATTRTYPE(SXFDict_LEADER_TERMINATOR);
	ADDATTRTYPE(SXFDict_TRIMMED_CURVE);
	ADDATTRTYPE(SXFDict_DRAWING_SHEET_REVISION);
	ADDATTRTYPE(SXFDict_TEXT_PATH);
	ADDATTRTYPE(SXFDict_INVISIBILITY_CONTEXT);
	ADDATTRTYPE(SXFDict_GEOMETRIC_SET_SELECT);
	ADDATTRTYPE(SXFDict_ANNOTATION_SYMBOL);
	ADDATTRTYPE(SXFDict_SYMBOL_REPRESENTATION);
	ADDATTRTYPE(SXFDict_PRESENTATION_REPRESENTATION);
	ADDATTRTYPE(SXFDict_TEXT_OR_CHARACTER);
	ADDATTRTYPE(SXFDict_SI_UNIT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_ELEMENTS);
	ADDATTRTYPE(SXFDict_BOX_ROTATE_ANGLE);
	ADDATTRTYPE(SXFDict_DRAWING_DEFINITION);
	ADDATTRTYPE(SXFDict_SYMBOL_REPRESENTATION_MAP);
	ADDATTRTYPE(SXFDict_CURVE_STYLE_FONT);
	ADDATTRTYPE(SXFDict_TRIMMING_SELECT);
	ADDATTRTYPE(SXFDict_ANNOTATION_CURVE_OCCURRENCE);
	ADDATTRTYPE(SXFDict_PLACEMENT);
	ADDATTRTYPE(SXFDict_LEADER_CURVE);
	ADDATTRTYPE(SXFDict_FILL_AREA_STYLE_TILE_SHAPE_SELECT);
	ADDATTRTYPE(SXFDict_BOX_HEIGHT);
	ADDATTRTYPE(SXFDict_GEOMETRIC_REPRESENTATION_CONTEXT);
	ADDATTRTYPE(SXFDict_CURVE_STYLE);
	ADDATTRTYPE(SXFDict_SOURCE_ITEM);
	ADDATTRTYPE(SXFDict_PRESENTATION_STYLE_SELECT);
	ADDATTRTYPE(SXFDict_CONTRACTED_ITEM);
	ADDATTRTYPE(SXFDict_LINE);
	ADDATTRTYPE(SXFDict_INVISIBILITY);
	ADDATTRTYPE(SXFDict_STYLED_ITEM);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_CURVE_FONT);
	ADDATTRTYPE(SXFDict_FILL_AREA_STYLE_TILES);
	ADDATTRTYPE(SXFDict_TERMINATOR_SYMBOL);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_COLOUR);
	ADDATTRTYPE(SXFDict_DERIVED_UNIT_ELEMENT);
	ADDATTRTYPE(SXFDict_EXTERNALLY_DEFINED_HATCH_STYLE);
	ADDATTRTYPE(SXFDict_LABEL);
	ADDATTRTYPE(SXFDict_DRAUGHTING_DRAWING_REVISION);
	ADDATTRTYPE(SXFDict_VECTOR);
	ADDATTRTYPE(SXFDict_NULL_STYLE);
	ADDATTRTYPE(SXFDict_PRESENTATION_SIZE);
	ADDATTRTYPE(SXFDict_EXTERNALLY_DEFINED_SYMBOL);
	ADDATTRTYPE(SXFDict_PRESENTATION_LAYER_USAGE);
	ADDATTRTYPE(SXFDict_SYMBOL_STYLE_SELECT);
	ADDATTRTYPE(SXFDict_LINEAR_DIMENSION);
	ADDATTRTYPE(SXFDict_TEXT_STYLE_FOR_DEFINED_FONT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_CALLOUT);
	ADDATTRTYPE(SXFDict_AHEAD_OR_BEHIND);
	ADDATTRTYPE(SXFDict_CURVE_STYLE_FONT_SELECT);
	ADDATTRTYPE(SXFDict_FILL_AREA_STYLE_HATCHING);
	ADDATTRTYPE(SXFDict_BOX_SLANT_ANGLE);
	ADDATTRTYPE(SXFDict_DRAWING_SHEET_REVISION_USAGE);
	ADDATTRTYPE(SXFDict_ANNOTATION_TEXT_OCCURRENCE);
	ADDATTRTYPE(SXFDict_TEXT_STYLE_WITH_BOX_CHARACTERISTICS);
	ADDATTRTYPE(SXFDict_REPRESENTATION_MAP);
	ADDATTRTYPE(SXFDict_DIMENSION_CALLOUT_RELATIONSHIP);
	ADDATTRTYPE(SXFDict_AXIS2_PLACEMENT_2D);
	ADDATTRTYPE(SXFDict_CURVE_OR_RENDER);
	ADDATTRTYPE(SXFDict_B_SPLINE_SURFACE_FORM);
	ADDATTRTYPE(SXFDict_EXTERNALLY_DEFINED_TEXT_FONT);
	ADDATTRTYPE(SXFDict_CONIC);
	ADDATTRTYPE(SXFDict_CHARACTER_STYLE_SELECT);
	ADDATTRTYPE(SXFDict_TEXT_STYLE_WITH_SPACING);
	ADDATTRTYPE(SXFDict_PRESENTATION_SIZE_ASSIGNMENT_SELECT);
	ADDATTRTYPE(SXFDict_ONE_DIRECTION_REPEAT_FACTOR);
	ADDATTRTYPE(SXFDict_ELLIPSE);
	ADDATTRTYPE(SXFDict_MARKER_SELECT);
	ADDATTRTYPE(SXFDict_LENGTH_MEASURE_WITH_UNIT);
	ADDATTRTYPE(SXFDict_B_SPLINE_CURVE_FORM);
	ADDATTRTYPE(SXFDict_INVISIBLE_ITEM);
	ADDATTRTYPE(SXFDict_DIRECTION);
	ADDATTRTYPE(SXFDict_FILL_STYLE_SELECT);
	ADDATTRTYPE(SXFDict_COLOUR);
	ADDATTRTYPE(SXFDict_REPRESENTATION);
	ADDATTRTYPE(SXFDict_DRAWING_REVISION);
	ADDATTRTYPE(SXFDict_ANNOTATION_FILL_AREA_OCCURRENCE);
	ADDATTRTYPE(SXFDict_TEXT_STYLE);
	ADDATTRTYPE(SXFDict_B_SPLINE_CURVE);
	ADDATTRTYPE(SXFDict_FILL_AREA_STYLE_COLOUR);
	ADDATTRTYPE(SXFDict_CARTESIAN_POINT);
	ADDATTRTYPE(SXFDict_ANNOTATION_FILL_AREA);
	ADDATTRTYPE(SXFDict_ANNOTATION_OCCURRENCE);
	ADDATTRTYPE(SXFDict_UNIT);
	ADDATTRTYPE(SXFDict_PRESENTATION_REPRESENTATION_SELECT);
	ADDATTRTYPE(SXFDict_DIMENSION_CURVE_TERMINATOR);
	ADDATTRTYPE(SXFDict_POSITIVE_LENGTH_MEASURE);
	ADDATTRTYPE(SXFDict_BOX_CHARACTERISTIC_SELECT);
	ADDATTRTYPE(SXFDict_ANNOTATION_SUBFIGURE_OCCURRENCE);
	ADDATTRTYPE(SXFDict_DIMENSIONAL_EXPONENTS);
	ADDATTRTYPE(SXFDict_PLANE_ANGLE_UNIT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_ANNOTATION_OCCURRENCE);
	ADDATTRTYPE(SXFDict_CURVE_DIMENSION);
	ADDATTRTYPE(SXFDict_ANGULAR_DIMENSION);
	ADDATTRTYPE(SXFDict_TEXT_ALIGNMENT);
	ADDATTRTYPE(SXFDict_PLANAR_EXTENT);
	ADDATTRTYPE(SXFDict_POSITIVE_RATIO_MEASURE);
	ADDATTRTYPE(SXFDict_FILL_AREA_STYLE);
	ADDATTRTYPE(SXFDict_BEZIER_CURVE);
	ADDATTRTYPE(SXFDict_DIAMETER_DIMENSION);
	ADDATTRTYPE(SXFDict_DIMENSION_CURVE_DIRECTED_CALLOUT);
	ADDATTRTYPE(SXFDict_PLANE_ANGLE_MEASURE);
	ADDATTRTYPE(SXFDict_PRESENTABLE_TEXT);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_TEXT_FONT);
	ADDATTRTYPE(SXFDict_CIRCLE);
	ADDATTRTYPE(SXFDict_COLOUR_SPECIFICATION);
	ADDATTRTYPE(SXFDict_PROJECTION_CURVE);
	ADDATTRTYPE(SXFDict_DRAUGHTING_ORGANIZATION_ITEM);
	ADDATTRTYPE(SXFDict_COMPOSITE_CURVE_SEGMENT);
	ADDATTRTYPE(SXFDict_IDENTIFIER);
	ADDATTRTYPE(SXFDict_LENGTH_MEASURE);
	ADDATTRTYPE(SXFDict_TWO_DIRECTION_REPEAT_FACTOR);
	ADDATTRTYPE(SXFDict_TEXT);
	ADDATTRTYPE(SXFDict_PRE_DEFINED_MARKER);
	ADDATTRTYPE(SXFDict_DRAUGHTING_PRE_DEFINED_CURVE_FONT);
	ADDATTRTYPE(SXFDict_DIMENSION_CURVE);
	ADDATTRTYPE(SXFDict_COLOUR_RGB);
	ADDATTRTYPE(SXFDict_REPRESENTATION_CONTEXT);
	ADDATTRTYPE(SXFDict_PRESENTATION_AREA);
	ADDATTRTYPE(SXFDict_KNOT_TYPE);
	ADDATTRTYPE(SXFDict_DERIVED_UNIT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_GROUP_ELEMENT);
	ADDATTRTYPE(SXFDict_STRUCTURED_DIMENSION_CALLOUT);
	ADDATTRTYPE(SXFDict_TRIMMING_PREFERENCE);
	ADDATTRTYPE(SXFDict_RADIUS_DIMENSION);
	ADDATTRTYPE(SXFDict_TEXT_LITERAL_WITH_EXTENT);
	ADDATTRTYPE(SXFDict_GEOMETRIC_REPRESENTATION_ITEM);
	ADDATTRTYPE(SXFDict_PRESENTATION_LAYER_ASSIGNMENT);
	ADDATTRTYPE(SXFDict_SPECIFIED_ITEM);
	ADDATTRTYPE(SXFDict_DEFINED_SYMBOL);
	ADDATTRTYPE(SXFDict_CURVE_STYLE_FONT_PATTERN);
	ADDATTRTYPE(SXFDict_LAYERED_ITEM);
//	ADD(S)	Ver3.0対応	K.Naono	04.01.30
	ADDATTRTYPE(SXFDict_DAY_IN_MONTH_NUMBER);
	ADDATTRTYPE(SXFDict_MONTH_IN_YEAR_NUMBER);
	ADDATTRTYPE(SXFDict_DATE_TIME_SELECT);
	ADDATTRTYPE(SXFDict_CONTRACT_TYPE);
	ADDATTRTYPE(SXFDict_CONTRACT);
	ADDATTRTYPE(SXFDict_CONTRACT_ASSIGNMENT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_CONTRACT_ASSIGNMENT);
	ADDATTRTYPE(SXFDict_DATE);
	ADDATTRTYPE(SXFDict_CALENDAR_DATE);
	ADDATTRTYPE(SXFDict_APPROVAL_STATUS);
	ADDATTRTYPE(SXFDict_APPROVAL);
	ADDATTRTYPE(SXFDict_APPROVAL_DATE_TIME);
	ADDATTRTYPE(SXFDict_APPROVAL_ASSIGNMENT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_APPROVAL_ASSIGNMENT);
	ADDATTRTYPE(SXFDict_ORGANIZATION);
	ADDATTRTYPE(SXFDict_ORGANIZATION_ROLE);
	ADDATTRTYPE(SXFDict_ORGANIZATION_ASSIGNMENT);
	ADDATTRTYPE(SXFDict_DRAUGHTING_ORGANIZATION_ASSIGNMENT);
//	ADD(E)	Ver3.0対応	K.Naono	04.01.30
//	ADD(S)	Ver3.1対応	Y.Nishiki	2012.07.03
	ADDATTRTYPE(SXFDict_CLOTHOID);
//	ADD(E)	Ver3.1対応	Y.Nishiki	2012.07.03
END_REGISTER_TYPE
